### ISSUE TITLE
Get user attributes

### ISSUE THREAD

**Issue by felixpis** [ghdna/cognito-express#4]
First of all very nice plugin, simple and clear, exactly what I've looked for.
The question is there an option to get user attributes (like email for instance)?
When validating token, got response as user information, but I can't find there attributes.

**Comment by ghdna** [comment]
Thank you. Glad you like it. 

Yes, there is a way to get user attributes. The AccessToken that I've used in my example doesn't fetch all user attributes from AWS Cognito. The best you'll get is username thats used for login (in most case this is the email id)
So you should instead use the ID Token, which has a lot more information. 

Here's the response I get during in cognitoExpress.validate function when I pass AccessToken (which I assume you're doing too)
```javascript
{
    sub: '476d9f80-8293-4a83-b04b-3adce2ea93e0',
    event_id: '4e843f05-fb8e-11e7-bcab-e71054fbda6e',
    token_use: 'access',
    scope: 'aws.cognito.signin.user.admin',
    iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_fXlFff73t',
    exp: 1516201162,
    iat: 1516197562,
    jti: 'c799566f-d746-40ae-9e9b-eba437acd234',
    client_id: '6ud6upoqhndc7vcv104vlnalpn',
    username: 'ghdna@git.com'
}
```

And here's the response I get when I pass IdToken
```javascript
{ sub: '476d9f90-8293-4a83-b04b-3adce2ea93e0',
  aud: '7ud6upoqhndc7vcv104vlnalpn',
  email_verified: false,
  event_id: 'f3433f7a-fb9a-11e7-8665-0f38d03cca66',
  token_use: 'id',
  auth_time: 1516202831,
  iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_fXlFef73t',
  name: 'Gary Arora',
  'cognito:username': 'ghdna@git.com',
  exp: 1516206431,
  iat: 1516202831,
  email: 'ghdna@git.com' 
}
```

To do this, make sure you pass your IDToken from client to backend. You get this IDToken with AccessToken and RefreshToken during your login with AWS Cognito.

Then on backend, make sure you initialize cognito-express constructor with tokenuse="id" and pass in the IdToken instead of AccessToken to cognito-express for validation

**Comment by felixpis** [comment]
Thank you very much! It works!

**Comment by lardissone** [comment]
~~Do you know why IDToken may not be returning custom attributes with cognito-express but it does on the client with aws-amplify?~~

**Update:** I had to logout and login again to get a new IDToken with the newly created custom attribute.
